[general]
import = [
	"~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]

[font]
normal = { family = "IosevkaTermNerdFont" }
size = 14

[window]
dimensions = { columns = 110, lines = 34 }
